apiVersion: apps/v1
kind: Deployment
metadata:
  name: myresto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myresto
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: myresto
    spec:
      containers:
      - name: myresto
        image: alexisendy/myresto
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: auth-configmap
        - secretRef:
            name: auth-secret
