node {
  stage("Clone the project") {
    git branch: 'master', url: 'https://github.com/Endy02/exam'
    sh "cd exam/myresto"
  }

  stage("Compilation") {
    sh "./mvnw clean install -DskipTests"
  }

  stage("Tests") {
    stage("Runing unit tests") {
      sh "./mvnw test -Punit"
    }
  }
}